version: '3.8'

services:
  hw_db:
    image: postgres:12-alpine
    container_name: backend_structure_db
    environment:
      POSTGRES_DB: postgres1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - './.docker_pgdata:/var/lib/postgresql/data'
    ports:
      - '5466:5432'
